### ISSUE TITLE
It seems not possible to override variables

### ISSUE THREAD

**Issue by ltarasiewicz** [infOpen/ansible-role-base-packages#2]
I've noticed that it does not seem possible to override/app packages to be installed by this role.

Although, you make `base_packages_simples_list : []` available in `defaults/main.yml` - which would suggest that the role is a good fit overriding/adding packages, this same list is defined in `vars/Debian.yml` and already populated with items. Since `vars/Debian.yml` is higher on variable precedence hierarchy (higher than host/group or playbook vars), it's not possible to override the list `base_packages_simples_list`. 

What seems to be left is modifying the list directly, but then reusability of the role is lost.

**Comment by achaussier** [comment]
Thanks, resolved in 0.2.0
